services:
  db:
    image: jager/db:latest
    build: 
      context: .
      dockerfile: Dockerfile-db
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: blog
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    image: jager/web:latest
    build:
      context: .
      dockerfile: Dockerfile-web
    ports: 
      - "3000:3000"
    environment:
        PORT: 3000
        JAEGER_SAMPLER_TYPE: "const"
        JAEGER_SAMPLER_PARAM: 1
        JAEGER_SAMPLER_MANAGER_HOST_PORT: "jaeger:5778"
        JAEGER_REPORTER_LOG_SPANS: "true"
        JAEGER_AGENT_HOST: "jaeger"
        JAEGER_AGENT_PORT: 6831
    depends_on:
        - loadbalancer
        - logservice

  dataservice:
      image: jager/dataservice:latest
      build:
        context: .
        dockerfile: Dockerfile-dataservice
      ports:
         - "4000:4000"
      environment:
          LISTEN_PORT: 4000
          JAEGER_SAMPLER_TYPE: "const"
          JAEGER_SAMPLER_PARAM: 1
          JAEGER_SAMPLER_MANAGER_HOST_PORT: "jaeger:5778"
          JAEGER_REPORTER_LOG_SPANS: "true"
          JAEGER_AGENT_HOST: "jaeger"
          JAEGER_AGENT_PORT: 6831
          DB_HOST: db
          DB_PORT: 3306
          DB_PASSWORD: toor
          DB_NAME: blog
      depends_on:
        - db

  loadbalancer:
    image: jager/loadbalancer:latest
    build:
      context: .
      dockerfile: Dockerfile-loadbalancer
    ports:
      - "2000:2000"
      - "2001:2001"
    environment:
        JAEGER_SAMPLER_TYPE: "const"
        JAEGER_SAMPLER_PARAM: 1
        JAEGER_SAMPLER_MANAGER_HOST_PORT: "jaeger:5778"
        JAEGER_REPORTER_LOG_SPANS: "true"
        JAEGER_AGENT_HOST: "jaeger"
        JAEGER_AGENT_PORT: 6831
    command: -logservice http://logservice:6000
    depends_on:
      - logservice

  logservice:
    image: jager/logservice:latest
    build:
      context: .
      dockerfile: Dockerfile-logservice
    ports:
      - "6000:6000"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    restart: on-failure


volumes:
 mysql_data: