FROM mysql:8.0.29

ENV MYSQL_DATABASE blog
ENV MYSQL_ROOT_PASSWORD toor

COPY ./db/migrations/*.up.sql /docker-entrypoint-initdb.d/
RUN chmod -R 777 /docker-entrypoint-initdb.d/

CMD ["--default-authentication-plugin=mysql_native_password"]