name: Build & Push Docker Images to AWS ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push Docker Compose Services
        run: |
          docker compose -f docker-compose.yaml build

          # List of services to build and push to ECR
          SERVICES=("db" "web" "dataservice" "loadbalancer" "logservice")

          for SERVICE in "${SERVICES[@]}"; do
            echo "Pushing image for $SERVICE..."

            # Tag the image with the ECR repo URL
            docker tag "$SERVICE:latest" "${{ secrets.ECR_REGISTRY }}/jager/$SERVICE:latest"

            # Push the image to ECR
            docker push "${{ secrets.ECR_REGISTRY }}/jager/$SERVICE:latest"
          done
