name: Jager CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Setups:
    name: Setups
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Verify Go Installation
        run: go version

      - name: Ensure go.sum Exists
        run: |
          if [ ! -f go.sum ]; then
            echo "go.sum not found, running go mod tidy..."
            go mod tidy
          fi

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint for each service
        run: |
          for dir in dataservice db loadbalancer logservice web; do
            if [ -f "$dir/go.mod" ]; then
              echo "Running golangci-lint for $dir..."
              cd "$dir"
              golangci-lint run --timeout=5m --out-format=colored-line-number
              cd ..
            else
              echo "Skipping $dir (no go.mod found)"
            fi
          done
     
