name: Jager CI/CD

on:
  push:
    branches:
      - main  # Runs on every push to main
  pull_request:
    branches:
      - main  # Runs on every pull request to main
  workflow_dispatch:

jobs:
  Setups:
    name: Setups
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: "Set up Go"
        uses:  actions/checkout@v4
        with:
          go-version: '1.21'
      
      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true