name: Jager CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Setups:
    name: Setups
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: |
          for d in dataservice db loadbalancer logservice web; do
            echo "Installing dependencies in $d"
            (cd "$d" && go mod tidy && go mod download)
          done

      - name: Build Go Binaries
        run: |
          mkdir -p bin
          for d in dataservice db loadbalancer logservice web; do
            echo "Building $d"
            go build -o "bin/$d" "./$d"
          done
