name: Jager CI/CD

on:
  push:
    branches:
      - main  # Runs on every push to main
  pull_request:
    branches:
      - main  # Runs on every pull request to main
  workflow_dispatch:

jobs:
  Setups:
    name: Setups
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: "Set up Go"
        uses:  actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Ensure go.sum Exists
        run: |
          for dir in dataservice loadbalancer logservice web; do
            if [ -f "$dir/go.mod" ]; then
              echo "Generating go.sum for $dir..."
              (cd "$dir" && go mod tidy)
            else
              echo "Skipping $dir (no go.mod found)"
            fi
          done

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run Linter for Each Microservice
        run: |
          for dir in dataservice loadbalancer logservice web; do
            if [ -f "$dir/go.mod" ]; then
              echo "Running golangci-lint for $dir..."
              (cd "$dir" && golangci-lint run --out-format=colored-line-number) || exit 1
            else
              echo "Skipping $dir (no go.mod found)"
            fi
          done
          