name: Jager CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Setups:
    name: Setups
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Go Binaries
        run: |
          go build -o bin/dataservice ./dataservice
          go build -o bin/db ./db
          go build -o bin/loadbalancer ./loadbalancer
          go build -o bin/logservice ./logservice
          go build -o bin/web ./web
