name: Build and Push Docker Images using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: your_aws_account_id
      AWS_REGION: your_aws_region

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Compose Services
      run: |
        REPO_NAME="jager"
        ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        
        for service in $(docker compose -f docker-compose.yaml config --services); do
          echo "Building and pushing service: $service"
          
          # Build the service
          docker compose -f docker-compose.yaml build $service
          
          # Tag the image with the ECR repository URI
          docker tag ${service}:latest ${ECR_REGISTRY}/${REPO_NAME}/${service}:latest
          
          # Push the image to ECR
          docker push ${ECR_REGISTRY}/${REPO_NAME}/${service}:latest
        done
