name: Jager CI/CD
on: 
push:
    branches:
      - main
    pull_request:
      branches:
      - main
    workflow_dispatch:

jobs:
  Setups:
    name: Setups
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
